# Generated by Django 3.2.12 on 2023-09-18 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0002_auto_20230918_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='violatordata',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CarData',
        ),
    ]
