# Generated by Django 3.2.12 on 2023-09-22 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20230922_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeofmonthdata',
            old_name='user',
            new_name='register_by',
        ),
        migrations.RenameField(
            model_name='violatordata',
            old_name='user',
            new_name='register_by',
        ),
    ]
