# Generated by Django 3.2.12 on 2023-09-20 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0002_qrcodedata_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodedata',
            name='admin_pic',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.customuser'),
            preserve_default=False,
        ),
    ]
