# Generated by Django 3.2.12 on 2023-09-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20230920_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydata',
            old_name='arriving_at',
            new_name='arriving_date',
        ),
        migrations.RenameField(
            model_name='deliverydata',
            old_name='admin_pic',
            new_name='registered_by',
        ),
        migrations.RenameField(
            model_name='deliverydata',
            old_name='code_data',
            new_name='tracking_number',
        ),
    ]
