# Generated by Django 3.2.12 on 2023-09-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodedata',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
