# Generated by Django 3.2.12 on 2023-09-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_qrcodedata_admin_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodedata',
            name='receiver_check',
        ),
    ]
