# Generated by Django 3.2.12 on 2023-09-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20230920_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverydata',
            options={'verbose_name_plural': 'Delivery Data'},
        ),
    ]
