# Generated by Django 3.2.12 on 2023-09-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_deliverydata_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydata',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
