# Generated by Django 3.2.12 on 2023-09-20 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitordata',
            name='status',
            field=models.ForeignKey(default='Requested', on_delete=django.db.models.deletion.CASCADE, to='visitor.approvalstatus'),
            preserve_default=False,
        ),
    ]
