# Generated by Django 3.2.12 on 2023-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0007_auto_20230929_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitordata',
            old_name='security_team_leader_appoval',
            new_name='security_leader_appoval',
        ),
        migrations.RenameField(
            model_name='visitordata',
            old_name='reason',
            new_name='security_leader_appoval_reason',
        ),
        migrations.AddField(
            model_name='visitordata',
            name='security_manager_approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitordata',
            name='team_leader_approval_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
