# Generated by Django 3.2.12 on 2023-08-17 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reinvent', '0003_alter_reinventdata_request_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinventdata',
            name='lateday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reinventdata',
            name='requestday',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
