# Generated by Django 3.2.12 on 2023-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20230918_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeofmonthdata',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeofmonthdata',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
