# Generated by Django 3.2.12 on 2023-09-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_alter_truckdata_checkout_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckdata',
            name='checkin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
