# Generated by Django 3.2.12 on 2023-09-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_alter_truckdata_checkin_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckdata',
            name='load_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='truckdata',
            name='out_trailer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
