# Generated by Django 3.2.12 on 2023-09-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_auto_20230925_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdata',
            name='file',
            field=models.FileField(default='1', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
