# Generated by Django 3.2.12 on 2023-09-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0005_truckdata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
