# Generated by Django 3.2.12 on 2023-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0006_alter_truckdata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='truckdata',
            name='file',
        ),
    ]
