# Generated by Django 3.2.12 on 2023-09-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0007_auto_20230925_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileData',
        ),
    ]
