# Generated by Django 4.2 on 2023-09-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0008_delete_filedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckdata',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
