# Generated by Django 3.2.12 on 2023-09-20 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Requested', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Approval Status',
            },
        ),
        migrations.CreateModel(
            name='VisitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_company', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('visitor_purpose', models.TextField()),
                ('bring_laptop', models.CharField(max_length=255)),
                ('pic_contact', models.IntegerField(blank=True, null=True)),
                ('register_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.approvalstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
