# Generated by Django 3.2.12 on 2023-09-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_auto_20230922_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitordata',
            name='pic_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
