# Generated by Django 3.2.12 on 2023-09-29 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_auto_20230929_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitordata',
            old_name='security_admin_approval',
            new_name='security_manager_approval',
        ),
        migrations.RenameField(
            model_name='visitordata',
            old_name='your_team_manager_approval',
            new_name='team_leader_approval',
        ),
    ]
