# Generated by Django 3.2.12 on 2023-09-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0009_auto_20230929_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitordata',
            name='security_leader_appoval_time',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='visitordata',
            name='security_manager_approval_time',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='visitordata',
            name='team_leader_approval_time',
            field=models.DateField(default=''),
        ),
    ]
