# Generated by Django 3.2.12 on 2023-08-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinvent', '0002_reinventdata_request_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinventdata',
            name='request_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
