# Generated by Django 3.2.12 on 2023-08-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reinvent', '0004_auto_20230817_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reinventdata',
            old_name='requestday',
            new_name='appliedday',
        ),
    ]
