# Generated by Django 3.2.12 on 2023-08-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reinvent', '0006_auto_20230817_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinventdata',
            name='credit',
        ),
    ]
