# Generated by Django 3.2.12 on 2023-08-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reinvent', '0007_remove_reinventdata_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reinventdata',
            name='remark',
            field=models.TextField(blank=True, max_length=76, null=True),
        ),
    ]
